# Generated by Django 4.0.4 on 2022-05-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceItem',
            new_name='Pending_Fees',
        ),
    ]
